### ISSUE TITLE
add images

### ISSUE THREAD

**Issue by marcionitao** [marcionitao/estradasDW#1]
![capturar](https://cloud.githubusercontent.com/assets/3647246/26784685/3021c87c-49ff-11e7-9069-c4100e2e2d5b.PNG)
![capturar_2](https://cloud.githubusercontent.com/assets/3647246/26784689/3290d166-49ff-11e7-9552-f958668113fd.PNG)
![capturar_3](https://cloud.githubusercontent.com/assets/3647246/26784693/36858c4e-49ff-11e7-86cf-9ba837783e1d.PNG)
![capturar_4](https://cloud.githubusercontent.com/assets/3647246/26784695/3a2732d0-49ff-11e7-9881-4db3c2ac0288.PNG)
![capturar_5](https://cloud.githubusercontent.com/assets/3647246/26784698/3ca0542e-49ff-11e7-849e-7e78971f2b94.PNG)

**Comment by a21002704** [comment]
nossa veio, de onde veio isto?? Volto à vida do passado? kkkkkk

2017-06-05 13:57 GMT+01:00 Márcio Nitão <notifications@github.com>:
